services:
  app:
    container_name: antimess
    image: antimess-backend
    build: 
      context: ./springboot-backend/
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    expose:
      - 8088
    restart: always
    # network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//host.docker.internal:1521/orclpdb
      SPRING_DATASOURCE_USERNAME: antimess
      SPRING_DATASOURCE_PASSWORD: antimess
      # SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.OracleDialect
      # SPRING_JPA_GENERATE-DDL: true

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
        - 27017:27017
    volumes:
        - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
       - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}
